spring:
  # 数据库连接 zeroDateTimeBehavior=convertToNull控制时间戳数据0000-00-00 00：00：00不报错，转换为null
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  # 配置mapper.xml文件存放路径
  mapper-locations: classpath:mapper/*.xml
  # pojo别名包扫描
  type-aliases-package: com.example.pojo.User

server:
  port: 8081
  servlet:
    # 配置项目虚拟目录
    context-path: /api
